server:
  port: 0
  # TODO - java -jar -Dserver.port=9003
  # TODO - 혹은 ./gradlew bootRun -Dserver.port=9003
  # TODO - 으로 port 변경 후 jar 구동 가능

  # TODO - port를 '0'으로 기재할 경우 random port를 사용한다는 의미
  # TODO - 매번 실행 시 port가 변경된다.

  # TODO - 그러나 Eureka에서는 server.port를 기준으로 applcation.name을 등록하기 때문에
  # TODO - spring application이 다중으로 구동되더라도 마지막에 실행한 application server만 등롣될 것이다.
  # TODO - 해결법으로 eureka.instance.instance-id 사용

spring:
  application:
    name: user-service
  h2:
    console:
      enabled: true
      # TODO - 외부에서 접속가능하도록 설정
      settings:
        web-allow-others: true
      path: /h2-console
  # TODO - datasource가 없다며 Entity에 맞는 테이블이 자동으로 생성되지 않는다.
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    # TODO - Eureka에 현재의 Client Micro Service 정보를 등록함을 설정
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

greeting:
  message: Welcom to the Simple E-commerce.

logging:
  level:
    com.citizen.userservice: DEBUG

token:
  expiration_time: 84_600_000
  secret: citizen