server:
  # TODO - random port 사용 시 '0'으로 입력
  # TODO - 하지만 Eureka에서는 Server Instance를 여러개 띄워도,
  # TODO - port가 0인 Instance 하나만 잡히기 때문에 주의를 요한다.
  port: 0

spring:
  application:
    name: first-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    # TODO - random port 실행 시 Eureka에 각기 다른 instance id를 부여하기 위함
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
